main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Reading
    url: /reading/
    weight: 3
  - name: Class
    url: /class/
    weight: 4
  - name: Homework
    url: /homework/
    weight: 5
  - name: Useful
    url: /useful/
    weight: 6
  - name: "<i class=\"fab fa-slack\"></i>"
    url: https://vis-for-gds.slack.com
    weight: 7

reading:
  - name: Overview
    weight: 1

class:
  - name: Overview
    weight: 1

homework:
  - name: Overview
    weight: 1
