main:
  - name: Overview
    url: /overview/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Reading
    url: /reading/
    weight: 3
  - name: Class
    url: /class/
    weight: 4



reading:
  - name: Overview
    weight: 1

class:
  - name: Overview
    weight: 1

homework:
  - name: Overview
    weight: 1
