baseurl: "https://www.roger-beecham.com/vis-for-gds/"
defaultContentLanguage: "en-uk"
title: "Introduction to Geographic Data Science"
theme: hugo-academic/wowchemy
canonifyURLs: true
relativeURLs: true
security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
# ------------------
# Building options
# ------------------
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: True

# No taxonomy
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  

copyright: ''
enableGitInfo: true
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true
paginate: 10
enableEmoji: true
footnotereturnlinkcontents: <sup>^</sup>


# ----------------
# Output options
# ----------------
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rproj.user$
  - \.Rhistory$
  - \.knit\\.md$
  - \.utf8\\.md$
  - _files$
  - _cache$
  - \.graffle$
  - \.pdf$
