---
title: "Introduction to Geographic Data Science"
author: "Francisco Rowe ([`@fcorowe`](http://twitter.com/fcorowe))"
date: "`r Sys.Date()`"
output: tint::tintHtml
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tint)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tint'))
options(htmltools.dir.version = FALSE)
```

```{marginfigure}
[**Next**](01-gds.html)
```

# Description

This workshops offers an introduction to *Geographic Data Science*. It provides an introduction to fundamental concepts of geographic data science using a hands-on approach in *R*. It offers an overview of various types of spatial data, key challenges of working with these data, and some basic analytical techniques. 

# Structure

The workshop is structured as follows:

* [**What is geographic data science?**](01-gds.html)
* [**Spatial data**](02-spatial-data.html)  
* [**Spatial weights**](03-spatial_weights.html)  
* [**Spatial autocorrelation**](04-spatial_econometrics.html)  


# Resources

All this course material is available on Github and you can download it [**here**](https://github.com/fcorowe/udd_gds_course/archive/refs/heads/main.zip). Once you have download it, ensure it is in a safe place on your computer.

# Computational Environment

You need the most recent version of R and packages. These can be installed following the instructions provided in our [R installation guide](https://gdsl-ul.github.io/r_install/).

## Dependency list

Ensure you have installed the list of libraries used:

* `knitr`
* `leaflet`
* `rgdal`
* `sf`
* `sp`
* `spdep`
* `tidyverse`
* `tint`
* `tmap`
* `viridis`
* `viridisLite`


You can get the materials from this course as a [download](https://github.com/fcorowe/intro-gds/archive/refs/heads/main.zip) of a .zip file or by going directly to the [GitHub repository](https://github.com/fcorowe/intro-gds).


