---
title: Syllabus
slug: syllabus
citeproc: true
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
      toc: TRUE
---

```{r load-libraries, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

<!-- [^courseinfo]: {-}
  `r blogdown::shortcode("courseinfo")` -->


## Overview

In modern data analysis, graphics and computational statistics are increasingly used together to explore and identify complex patterns in data and to make and communicate claims under uncertainty. This course will go beyond traditional ideas of charts, graphs, maps (and also statistics!) to equip you with the critical analysis, design and technical skills to analyse and communicate with geographic datasets.

The course emphasises real-world applications. You will work with both new, large-scale behavioural datasets, as well as more traditional, administrative datasets located within various social science domains: Political Science, Crime Science, Urban and Transport Planning. As well as learning how to use graphics and statistics to explore patterns in these data, implementing recent ideas from data journalism you will learn how to communicate research findings – how to tell stories with data.

## Module objectives

By the end of the course you will:

1.	Describe, process and combine geographic datasets from a range of sources
2.	Design statistical graphics that expose structure in geographic data and that are underpinned by established principles in information visualization and cartography
3.	Use modern data science and visualization frameworks to produce coherent, reproducible data analyses
4.	Apply modern statistical techniques for analysing, representing and communicating data and model uncertainty

## Assessment

A detailed and formal description of the Assessment for this module can be found on the [Minerva](https://minerva.leeds.ac.uk/webapps/blackboard/content/listContentEditable.jsp?content_id=_7985647_1&course_id=_521510_1&mode=reset) pages. The summative assessment consists of:

* 30% - Portfolio of work from completing session [homeworks](/homework/) 2-5 (1500 word equivalent)
* 70% - Visual data analysis report (2500 word equivalent)

## Software

All work in the module -- data collection, analysis and reporting -- will be completed using [`R`](https://www.r-project.org/) and the [`RStudio`](https://rstudio.com/) [Integrated Development Environment](https://en.wikipedia.org/wiki/Integrated_development_environment) (IDE). Along with [`Python`](https://www.python.org/) `R` is *the* programming environment for modern data analysis.

## Module breakdown

`r blogdown::shortcode("schedule")`

## Navigating the course materials

The home for this module is [this website](../../). From here, you will find the course [Schedule](/schedule/) (also above), where for each session there is <i class="fas fa-book-reader"></i> [**Reading**](/reading/), <i class="fas fa-chalkboard-teacher"></i> [**Class**](/class/) content and <i class="fas fa-laptop-code"></i> [**Homework**](/homework/). Also accompanying each session is an [R Markdown](https://rmarkdown.rstudio.com/) file with a template to complete coding activities introduced through the [class](/class/) and [homework](/homework/) pages. These session templates contain pre-prepared code chunks for you to execute.  As the module progresses and you become more familiar and competent in `R`, you will be required to contribute more code of your own to these.

As you work through the course materials you will notice special icons are used to distinguish **learning outcomes** <i class="fas fa-chevron-circle-down"></i> and **instructions**  <i class="fas fa-tasks"></i> that need to be completed, along with important informational asides <i class="fas fa-info-circle"></i>. Do pay special attention to these, and in particular revisit the **learning outcomes** <i class="fas fa-chevron-circle-down"></i> as you progress through the sessions.

 Use [Minerva](https://minerva.leeds.ac.uk/) to access the [Module  Handbook](https://minerva.leeds.ac.uk/webapps/blackboard/execute/announcement?method=search&context=course&course_id=_521510_1&handle=cp_announcements&mode=cpview) and to upload assignments in the usual way.

## Self-guided learning

> The bad news is whenever you’re learning a new tool, for a long time you’re going to suck. It's going to be very frustrating. But, the good news is that that is typical, it’s something that happens to everyone, and it’s only temporary ... [T]here is no way to go from knowing nothing about a subject to knowing something about a subject and being an expert in it without going through a period of great frustration."
>
> Hadley Wickham

From the module overview and outline you will have got the sense that this is a reasonably technical module. You will be introduced to the key components of modern data analysis (Data Science) through doing -- the course inevitably requires you to do a fair amount of "coding", in this case in `R`.

It is understandable if this feels like a daunting prospect. The barrier to entry is greater than with point-and-click interfaces such as ArcGIS and SPSS. So do expect that this module  may require a degree of patience and persistence -- but isn't that true of all things that are worth learning?

In order reduce the pain, I've tried to include within the module a balance of content between programming fundamentals, theoretical/conceptual learning and more procedural 'grunt-work' with datasets. I have also carefully considered and incorporated ideas from some of the really high quality [Resources](../useful) out there aimed at lowering the barrier to doing Data Science in `R`.

In return, I expect you to:

* **Read** all course materials
* **Complete** the class session tasks, homework and coursework assignment
* **Participate** in the discussion forum

## Slack

A key mechanism through which you can **participate** is by contributing to the discussion forum. Engaging fully with this will help to foster a sort of collegiate atmosphere on the module that will maximise your learning. I have set up a course [Slack](https://vis-for-gds.slack.com), which should provide a useful mechanism for sharing information, resources and importantly posting and discussing `code`.

If you've not used Slack before, then follow these pages on [getting started with Slack](https://slack.com/intl/en-gb/help/articles/218080037-Getting-started-for-new-members). You should post all substantive questions associated with the module to Slack. These will get answered. If you wish to discuss more personal matters around your completing the course, then send those directly to me via e-mail.

{{% callout instruction %}}
Create an account on the [vis-for-gds Slack](https://vis-for-gds.slack.com). Be sue to register with you `.leeds.ac.uk` e-mail. If you run into any problems, try [getting started with Slack](https://slack.com/intl/en-gb/help/articles/218080037-Getting-started-for-new-members).
{{% /callout  %}}

## Asking questions

As many of you will be learning to program in R for the first time, you should expect to be baffled at times and to routinely encounter scary-looking `ERROR` messages. Counterintuitively, this is actually to be welcomed. You need to be making mistakes and hitting obstacles on a regular basis if you are to progress.

*How* you respond to these obstacles is important. In a face-to-face lab, the temptation when hitting a problem is to raise your hand, gesture towards your screen and have a demonstrator 'de-bug' for you. Whilst this may initially seem like an efficient solution, you risk learning very little if this is your only course of action.

When you encounter problems working through the material in this course, try to force yourself to spend 15-20 minutes troubleshooting the problem individually. [Google](https://www.google.com/) your problem or try [StackOverflow](https://stackoverflow.com/). If you are not able to resolve the problem on your own, then post your question to the course [Slack](https://vis-for-gds.slack.com), which I will monitor regularly. When doing this, make an effort to be specific and unambiguous about your problem. You might wish to consult StackOverflow's guidance on [how to ask a good question](https://stackoverflow.com/help/how-to-ask).
