---
title: Useful
slug: useful
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
      toc: TRUE
---

## Primers

- [@healy_data_2018]\
-- An engaging read that manages to integrate ggplot2 code with key Information Visualization theory and using real social science datasets.\
[Free online (draft version)](https://socviz.co/).


- [@lovelace_geocomputation_2019]\
-- This book comprehensively introduces spatial data handling in R. It is a great complement to R for Data Science in that it draws on brand new libraries that support `tidyverse-style` operations on spatial data.\
[Free online](https://geocompr.robinlovelace.net/).

- [@wickham_r_2017]\
-- _The_ primer for doing data analysis with R. Wickham and Grolemund present a thesis of the data science workflow and illustrates how R and packages that form the `tidyverse` support this. It is both accessible and coherent and is highly recommended.\
[Free online](https://r4ds.had.co.nz/).

- [@wilke_fundamentals_2019]\
-- Excellent resource -- comprehensively covers key theory and important emerging areas of visual data analysis (uncertainty visualization etc. with an R and `ggplot2` framing).\
[Free online](https://clauswilke.com/dataviz/).


## Blogs

- [Flowingdata](http://flowingdata.com) \
-- Nathan Yau, a former statistics PhD from UCLA, has maintained a data vis blog and online training materials for some time. Numerous excellent examples, on the most part implemented in R and `ggplot2`.

- [giCentre](https://www.gicentre.net)  \
-- World-leading group researching and developing geovisualization. Check out recent work on [litvis](https://www.gicentre.net/software#/litvis-1/) and [elm-vega](https://www.gicentre.net/elmvegalite/).


- [Multiple Views](https://medium.com/multiple-views-visualization-research-explained) \
-- Blog series by leading visualization researchers and practitioners.

## Conferences

- [IEEE VIS](http://ieeevis.org/)\
-- *The* conference at which leading Data Visualization work is published through a special issue of [Transactions on Visualization & Computer Graphics](https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=2945).

- [OpenVis Conf](http://www.openvisconf.com)\
-- New, exciting conference (though last one was in 2018!). Presenters are academics and practitioners. Videos of talks from previous conferences are published online. From the 2018 conference, I'd recommend Matt Kay's on [Uncertainty Visualization](https://www.youtube.com/watch?v=vqzO-9LSoG4&feature=youtu.be), Maarten Lambrechts' [Xenographics](https://www.youtube.com/watch?v=fp-WNqaQG0s&feature=youtu.be) and Heather Krause's [F-Word](https://www.youtube.com/watch?v=uw1Tag08dK4&feature=youtu.be).
