---
title: "Introduction"
linktitle: "1: Introduction"
date: "2022-05-09"
class_date: "2022-05-09"
citeproc: true
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
menu:
  homework:
    parent: Homework
    weight: 1
type: docs
weight: 1
editor_options:
  chunk_output_type: console
---

## Session Outcomes

By the end of this homework session you should:

{{% callout objective %}}
- [x] Be familiar with RStudio, R Markdown and R Projects.
- [x] Know how to install and enable R packages and query package documentation.
- [x] Understand the purpose R Markdown files and their anatomy.
- [x] Know how to create R Projects and understand their benefits
{{% /callout %}}

## Introduction

For most sessions I will post some additional exercises that relate to the practical learning you will be doing in-class. You will be populating R Markdown files as you complete the exercises. The exercises will vary in detail and challenge but you should try your best effort to complete them as they will form a portfolio of work that will contribute 30% of the module mark. Doing these exercises will also help you build the skills necessary to complete the project coursework that forms the main contribution to your module mark (70%).

There has been a lot to take in this session. There are no formal exercises to complete as part of this session's homework. Instead we want you to really try to solidify your understanding of the core technology for the module.

##  Task 1: **Read** and complete BasicBasics

[R-Ladies](https://en.wikipedia.org/wiki/R-Ladies) is an excellent initiative and the [R-Ladies Sydney BasicBasics](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-0/) pages are really great for introducing the R and RStudio ecosystem, and a little of the `tidyverse`.

Read and work your way through:

* [BasicBasics 1](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-1/)
* [BasicBasics 2](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-2/)
* [BasicBasics 3](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-3/)

This repeats some of the work that you have done in class this session. If you're entirely new to R programming, this repetition is probably useful (and necessary) at this stage.

## Task 2: **Watch** Thomas Mock's Introduction to Tidy Statistics

Thomas Mock's [Gentle Introduction to Tidy Statistics](https://rstudio.com/resources/webinars/a-gentle-introduction-to-tidy-statistics-in-r/) is pitched those coming to R after previously working with point-and-click interfaces (SPSS, STATA, ArcGIS). I strongly recommend that you watch this now as you start to embark on the "pain" of doing data analysis programmatically.


<!-- <div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://rstudio.com/resources/webinars/a-gentle-introduction-to-tidy-statistics-in-r/" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div> -->
